### ISSUE TITLE
noBackgroundSize not working

### ISSUE THREAD

**Issue by ivancuric** [imsky/holder#183]
Still outputs the background size property.

the JS:
```javascript
Holder.run({
  noBackgroundSize: true
});
```

The CSS:
```css
.hero {
  background-image: url(?holder.js/1920x400?theme=sky&text=%20);
}
```

The output:
```html
<div class="hero holderjs" data-background-src="holder.js/1920x400?theme=sky&amp;text=%20" data-holder-rendered="true" style="background-image: url(...); background-size: 1920px 400px;">
```
